// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_books from "./routes/api/books.ts";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $BookForm from "./islands/BookForm.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $Table from "./islands/Table.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/books.ts": $api_books,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BookForm.tsx": $BookForm,
    "./islands/Modal.tsx": $Modal,
    "./islands/Table.tsx": $Table,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
